INSERT INTO tb_camisa (title, club, camisa_year, manufacturer, short_description, img_url, long_description) VALUES ('Camisa Corinthians 2000', 'Sport Club Corinthians Paulista', 2000, 'Nike Football','Camisa utilizada na campanha do Mundial', 'https://github.com/lucasduarte98/imagens/blob/de0eb963938d9f780136956e3fbdc767674f3635/Corinthians%202000.png?raw=true', 'Símbolo da conquista do Mundial de 2000, a camisa é um clássico entre os torcedores, representando a história e a grandeza do Corinthians.');

INSERT INTO tb_camisa (title, club, camisa_year, manufacturer, short_description, img_url, long_description) VALUES ('Camisa Brasil 2002', 'Seleção Brasileira', 2002, 'Nike', 'Camisa usada na conquista do pentacampeonato mundial', 'https://github.com/lucasduarte98/imagens/blob/main/Brasil%202002.png?raw=true', 'Camisa do penta da Seleção em 2002, marcada pelo trio Ronaldo, Rivaldo e Ronaldinho e eternizada na história do futebol mundial.');

INSERT INTO tb_camisa (title, club, camisa_year, manufacturer, short_description, img_url, long_description) VALUES ('Camisa França 2006', 'Seleção Francesa', 2006, 'Adidas', 'Camisa utilizada na campanha do vice-campeonato mundial', 'https://github.com/lucasduarte98/imagens/blob/main/Franca%202006.png?raw=true', 'Camisa marcante da França em 2006, lembrada pela atuação de Zidane e a campanha até a final da Copa do Mundo.');

INSERT INTO tb_camisa (title, club, camisa_year, manufacturer, short_description, img_url, long_description) VALUES ('Camisa Corinthians 2012', 'Sport Club Corinthians Paulista', 2012, 'Nike', 'Camisa do título mundial sobre o Chelsea', 'https://github.com/lucasduarte98/imagens/blob/main/Corinthians%202012.png?raw=true', 'Camisa usada na conquista do Mundial de 2012 sobre o Chelsea, símbolo de uma das maiores glórias do clube.');

INSERT INTO tb_camisa (title, club, camisa_year, manufacturer, short_description, img_url, long_description) VALUES ('Camisa Manchester United 2007-08', 'Manchester United', 2008, 'Nike', 'Camisa do título da Champions League', 'https://github.com/lucasduarte98/imagens/blob/main/United%202008.png?raw=true', 'Camisa da conquista da Champions 2007-08, com Cristiano Ronaldo em destaque e vitória sobre o Chelsea na final.');

INSERT INTO tb_camisa (title, club, camisa_year, manufacturer, short_description, img_url, long_description) VALUES ('Camisa Barcelona 2008-09', 'FC Barcelona', 2009, 'Nike', 'Camisa da tríplice coroa sob Pep Guardiola', 'https://github.com/lucasduarte98/imagens/blob/main/Barcelona%202009.png?raw=true', 'Camisa da temporada histórica de 2008-09, com Messi, Xavi e Iniesta liderando o time na conquista da tríplice coroa.');

INSERT INTO tb_camisa (title, club, camisa_year, manufacturer, short_description, img_url, long_description) VALUES ('Camisa Milan 2008-09', 'AC Milan', 2009, 'Adidas', 'Camisa utilizada por Ronaldinho e outros brasileiros no clube', 'https://github.com/lucasduarte98/imagens/blob/main/Milan%202009.png?raw=true', 'Camisa clássica do Milan em 2009, utilizada por grandes craques brasileiros como Ronaldinho, Kaká e Pato.');

INSERT INTO tb_camisa (title, club, camisa_year, manufacturer, short_description, img_url, long_description) VALUES ('Camisa Liverpool 2004-05', 'Liverpool FC', 2005, 'Reebok', 'Camisa do título da Champions League em Istambul', 'https://github.com/lucasduarte98/imagens/blob/main/Liverpool%202005.png?raw=true', 'Camisa histórica do Liverpool na épica final da Champions 2005, com virada sobre o Milan em Istambul.');

INSERT INTO tb_camisa (title, club, camisa_year, manufacturer, short_description, img_url, long_description) VALUES ('Camisa Corinthians 2009', 'Sport Club Corinthians Paulista', 2009, 'Nike', 'Camisa da volta de Ronaldo ao futebol brasileiro', 'https://github.com/lucasduarte98/imagens/blob/main/Corinthians%202009.png?raw=true', 'Camisa usada por Ronaldo em sua volta ao Brasil, marcada pelos títulos do Paulista e da Copa do Brasil em 2009.');
